---
- name: configure | Configuring netdata
  template:
    src: netdata.conf.j2
    dest: "{{ netdata_config_file }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=rw,g=rw,o=
  notify: restart netdata
  become: true

- name: configure | Configure stream
  template:
    src: stream.conf.j2
    dest: "{{ netdata_stream_file }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=rw,g=rw,o=
  notify: restart netdata
  become: true
  when: netdata_stream_node == none or
        netdata_stream_node == master or
        netdata_stream_node == slave

- name: configure | Configure python.d.conf
  template:
    src: python.d.conf.j2
    dest: "{{ netdata_python_d_conf }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=rw,g=rw,o=
  notify: restart netdata
  become: true
  when: netdata_python_enabled is defined

- name: configure | Configure python plugins
  template:
    src: python-plugins.conf.j2
    dest: "{{ netdata_python_d }}/{{ item.name }}.conf"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=rw,g=rw,o=
  with_items: "{{ netdata_python_plugin_jobs }}"
  notify: restart netdata
  become: true
  when: netdata_python_plugin_jobs is defined

#- name: configure | Configure go.d.conf
#...

#- name: configure | Configure go plugins
#...
