---
- name: configure | Configuring netdata
  template:
    src: netdata.conf.j2
    dest: "{{ netdata_config_file }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=r,g=r,o=
  notify: restart netdata
  become: true

- name: configure | Configure stream
  template:
    src: stream.conf.j2
    dest: "{{ netdata_stream_file }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=r,g=r,o=
  notify: restart netdata
  become: true

- name: configure | Configure python.d.conf
  template:
    src: python.d.conf.j2
    dest: "{{ netdata_python_d_conf }}"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=r,g=r,o=
  notify: restart netdata
  become: true

- name: configure | Configure plugins
  template:
    src: python-plugins.conf.j2
    dest: "{{ netdata_python_d }}/{{ item.name }}.conf"
    owner: "{{ netdata_global_run_as_user }}"
    group: root
    mode: u=r,g=r,o=
  when: netdata_plugin_jobs is defined
  with_items: "{{ netdata_plugin_jobs }}"
  notify: restart netdata
  become: true
