---
- name: debian | Install Stretch Backports Dependencies
  when: ansible_distribution_release == 'stretch'
  apt:
    name: "{{ netdata_debian_9_bp_deps }}"
    state: present
    update_cache: yes
    default_release: stretch-backports

- name: debian | Install Dependencies
  apt:
    name: "{{ netdata_debian_deps }}"
    state: present
    update_cache: yes
  become: true

- name: debian | Install Netdata
  apt:
    name: "{{ netdata_debian_pkgs }}"
    state: latest
  become: true
