---
- name: debian | Update apt-cache
  apt:
    update_cache: yes

- name: debian | Install Netdata
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items: "{{ netdata_debian_pkgs }}"
