---

- name: Main - Configure Debian Repo
  ansible.builtin.include_tasks:
    file: debian_repo.yml
  when: ansible_os_family == "Debian" and netdata_configure_repo

- name: Main - Run Debian stuff
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_os_family == "Debian"

- name: Main - Configure Netdata
  ansible.builtin.include_tasks:
    file: config.yml
