---
# handlers file for ansible-netdata

- name: Reload systemd netdata
  ansible.builtin.systemd_service:
    name: "netdata"
    daemon_reload: true
  become: true
  listen: netdata_systemd_reload

- name: Restart netdata
  ansible.builtin.systemd_service:
    name: "netdata"
    state: "restarted"
    enabled: true
    masked: false
  become: true
  listen: netdata_systemd_restart

- name: Start Netdata
  ansible.builtin.systemd_service:
    name: "netdata"
    state: "started"
    enabled: true
    masked: false
  become: true
  listen: netdata_systemd_start

- name: Stop Netdata
  ansible.builtin.systemd_service:
    name: "netdata"
    state: "stopped"
    enabled: true
    masked: false
  become: true
  listen: netdata_systemd_stop
